apiVersion: apps/v1
kind: Deployment
metadata: 
name: omc-sample-app
spec: 
selector: 
    matchLabels:
    app: omc-sample-app
replicas: 1
template:
    metadata:
    labels: 
        app: omc-sample-app
    spec:
    containers:
    - name: omc-sample-app
        image: data-region.ocir.io/my-tenant/my-repo/omc-sample-app:latest 
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
name: omc-sample-app
spec:
selector:
    app: omc-sample-app
ports:
- protocol: "TCP"
    port: 8080
    targetPort: 8080
type: LoadBalancer


# kubectl apply -f omc-sample-svc.yaml